# Generated by Django 4.2.7 on 2026-01-20 13:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterCompanyProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('industry', models.CharField(max_length=100)),
                ('company_size', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1000+', '1000+ employees')], max_length=20)),
                ('founded_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2030)])),
                ('head_office_location', models.CharField(max_length=200)),
                ('gst_cin', models.CharField(blank=True, help_text='GST or CIN number', max_length=50, null=True)),
                ('company_registration_document', models.FileField(blank=True, help_text='Upload company registration certificate', null=True, upload_to='company_documents/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True, help_text='Admin notes for verification', null=True)),
                ('company_description', models.TextField(help_text='Describe your company')),
                ('mission_and_culture', models.TextField(blank=True, null=True)),
                ('benefits_and_perks', models.TextField(blank=True, help_text='Comma-separated benefits and perks', null=True)),
                ('office_address', models.TextField()),
                ('work_mode', models.CharField(choices=[('office', 'Office'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20)),
                ('office_photos', models.TextField(blank=True, help_text='JSON array of office photo file paths', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.OneToOneField(limit_choices_to={'role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
                'db_table': 'recruiter_company_profile',
            },
        ),
    ]
