# Generated by Django 4.2.7 on 2026-01-21 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship', 'Internship')], default='Full-time', max_length=20)),
                ('work_mode', models.CharField(choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], default='Remote', max_length=20)),
                ('experience', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='INR', max_length=10)),
                ('salary_period', models.CharField(default='annually', max_length=20)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True, help_text='JSON array of responsibilities', null=True)),
                ('requirements', models.TextField(blank=True, help_text='JSON array of requirements', null=True)),
                ('skills', models.TextField(blank=True, help_text='JSON array of skills', null=True)),
                ('benefits', models.TextField(blank=True, help_text='JSON array of benefits', null=True)),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.URLField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('application_method', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('email', 'Email')], default='internal', max_length=20)),
                ('application_link', models.URLField(blank=True, null=True)),
                ('application_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('screening_questions', models.TextField(blank=True, help_text='JSON array of questions', null=True)),
                ('publish_immediately', models.BooleanField(default=True)),
                ('featured_job', models.BooleanField(default=False)),
                ('job_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('recruiter', models.ForeignKey(limit_choices_to={'role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
