# Generated by Django 4.2.7 on 2026-01-21 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiter', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship', 'Internship')], max_length=20)),
                ('work_mode', models.CharField(choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('experience_level', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('salary_period', models.CharField(default='annually', max_length=20)),
                ('job_description', models.TextField()),
                ('key_responsibilities', models.TextField(blank=True, help_text='JSON array', null=True)),
                ('benefits_and_perks', models.TextField(blank=True, help_text='JSON array', null=True)),
                ('requirements', models.TextField(blank=True, help_text='JSON array', null=True)),
                ('required_skills', models.TextField(blank=True, help_text='JSON array', null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('apply_method', models.CharField(choices=[('platform', 'Platform'), ('external', 'External'), ('email', 'Email')], default='platform', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(limit_choices_to={'role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Post',
                'verbose_name_plural': 'Job Posts',
                'db_table': 'job_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
